### PR TITLE
Max URI length

### PR DESCRIPTION
**Pull request by fearphage**
Added a param to specify max URI length

```
-u, --maxuri length
```

This addresses half of issue #6.

### CODE REVIEW

**Comment by fearphage** [comment]
Related: Prevented the case where empty mhtml headers were added to the file.

**Comment by nzakas** [comment]
I finally got around to looking at this. The changes look good but they're causing two unit tests to fail. That either means the changes broke some existing functionality or changed the functionality such that the tests are no longer valid. Can you take a look?

**Comment by fearphage** [comment]
Can you confirm that they were passing before this change?

**Comment by nzakas** [comment]
Yes, and you can too my switching back to the current state of my repository.

**Comment by tivac** [comment]
Fixed the tests, sorry about all the Git noise Nicholas. 

Not quite sure if this was better or worse than the pull request in #25 but figured it was at least a bit more appropriate a venue since Phred did the majority of the work.

**Comment by nzakas** [comment]
Cool thanks. I'll take a look when I get a free second.

**Comment by nzakas** [comment]
Merged in.

**Pull request closed without merging**
