### PR TITLE
Skip image via inline comment test

### PR DESCRIPTION
**Pull request by RoryH**
Added test for skip image via inline comment functionality.

### CODE REVIEW

**Comment by nzakas** [comment]
Great, thanks! Sorry it's taken me so long to review, will try to get to it this week.

**Comment by cmelion** [comment]
Any plans to perform the pull?

**Comment by nzakas** [comment]
Yes, but I'm traveling and won't be able to do it until I return.

**Comment by nzakas** [comment]
Merged into repo.

**Comment by cmelion** [comment]
Thanks!

**Pull request closed without merging**
