### PR TITLE
Edited src/net/nczonline/web/cssembed/CSSURLEmbedder.java via GitHub

### PR DESCRIPTION
**Pull request by RoryH**
Removed duplicate logic
Added ability to skip images on lines that contain CSS comment like: /\* CssEmbed: SKIP */

### CODE REVIEW

**Comment by nzakas** [comment]
If you can make this case-insensitive, I'll happily merge it in.

**Comment by nzakas** [comment]
Doh sorry, completely missed the case insensitive options that was in there. I'll work on getting this in sometime this week.

**Comment by RoryH** [comment]
I integrated this today to our build today, works great. Thanks for your work and I'm happy to be able to contribute.

**Comment by nzakas** [comment]
Hey Rory,

Noticed that there aren't any unit tests that verify this new functionality. Can you please add some?

**Comment by RoryH** [comment]
Hi Nic,

I have added a pull request with a unit test for the image skip functionality...  I'm afraid I'm not a Java programmer normally so I'm not actually sure how to run and test the tests. If you can verify it for me that would be great. I'm usually just a JavaScripter and am not familiar with JUnit and how it works. I believe my attempted logic should be sound though :-/

**Comment by nzakas** [comment]
Hi Rory - Hmmm, committing a test that you haven't verified to be working doesn't seem like a good idea. Please try to run it yourself first. There are a lot of references online:

Standalone: 
http://junit.sourceforge.net/doc/faq/faq.htm#tests_1

With Netbeans:
http://netbeans.org/kb/docs/java/junit-intro.html

I use Netbeans for development and testing, as I find it easier.

**Comment by RoryH** [comment]
Hi Nic, Found a problem with my previous change and corrected this. Added a test for the CSS comment skipping selected images and all test now run and pass successful.

**Comment by nzakas** [comment]
Thanks, I'll try to get to this soon (sorry, time has escaped me recently!)

**Comment by cmelion** [comment]
This is a useful enhancement, any plans to do the pull?

**Comment by nzakas** [comment]
Yes, just trying to find the time since it won't merge automatically.

**Comment by nzakas** [comment]
Merged into repo.

**Comment by gbakernet** [comment]
The pull request for this closed issue assumes that there will be one url() and one skip directive per line in the source file. I found this to be an issue for css files that have been compressed prior to running CSSembed, or even written in a compact format when background url and cursor url on the same line. 

Edit: Coherence

**Comment by nzakas** [comment]
You're commenting on a closed issue that doesn't seem to relate to what you're describing. If you think you found a bug, please create a new issue with specific details about the problem.

**Comment by gbakernet** [comment]
Created issue https://github.com/nzakas/cssembed/issues/40

Great tool BTW.

**Pull request closed without merging**
